"""Reusable graph lens for agent memory and source knowledge graphs."""

from .artifacts import (
    GRAPHFAKOS_ARTIFACT_SCHEMA,
    graph_artifact_schema,
    graph_from_dict,
    load_graph_artifact,
    validate_graph_artifact_payload,
    write_graph_artifact,
)
from .adapters import (
    FileGraphProvider,
    FixtureGraphProvider,
    build_fixture_baseline_graph,
    build_fixture_graph,
    build_fixture_overlay_graphs,
)
from .models import (
    GraphFakosCitation,
    GraphFakosDiagnostics,
    GraphFakosEdge,
    GraphFakosGraph,
    GraphFakosNode,
    GraphFakosProvenance,
    GraphFakosRequest,
    GraphFakosScreen,
    GraphFakosSnapshot,
    GraphFakosVisual,
)
from .provider import (
    GraphFakosComparisonProvider,
    GraphFakosOverlayProvider,
    GraphFakosProvider,
    diagnose_graph,
    load_comparison_graph,
    load_overlay_graphs,
    load_provider_graph,
    validate_graph,
)
from .server import (
    LocalViewerHttpServer,
    LocalViewerServerResult,
    RenderPath,
    make_local_viewer_server,
    serve_local_viewer,
)
from .static import (
    GraphPreviewOutputPaths,
    build_graph_report,
    render_embeddable_html,
    render_graph_markdown_report,
    render_static_html,
    write_embeddable_html,
    write_graph_markdown_report,
    write_provider_graph_artifact,
    write_provider_preview_outputs,
    write_graph_report,
    write_static_html,
)
from .ui import (
    build_graph_diff,
    build_viewer_route,
    parse_viewer_request,
    query_syntax_reference,
    render_graph_fragment,
    render_graph_viewer,
    render_provider_path,
    screen_manifest,
)

__version__ = "0.0.1"
PACKAGE_STATUS = "semantic-alpha"
STABLE_IMPORT_ROOTS = (
    "graphfakos.artifacts",
    "graphfakos",
    "graphfakos.adapters",
    "graphfakos.contracts",
    "graphfakos.models",
    "graphfakos.provider",
    "graphfakos.render",
    "graphfakos.server",
    "graphfakos.static",
    "graphfakos.testing",
    "graphfakos.ui",
)

__all__ = [
    "PACKAGE_STATUS",
    "STABLE_IMPORT_ROOTS",
    "__version__",
    "FileGraphProvider",
    "FixtureGraphProvider",
    "GRAPHFAKOS_ARTIFACT_SCHEMA",
    "GraphPreviewOutputPaths",
    "GraphFakosComparisonProvider",
    "GraphFakosCitation",
    "GraphFakosDiagnostics",
    "GraphFakosEdge",
    "GraphFakosGraph",
    "GraphFakosNode",
    "GraphFakosOverlayProvider",
    "GraphFakosProvider",
    "GraphFakosProvenance",
    "GraphFakosRequest",
    "GraphFakosScreen",
    "GraphFakosSnapshot",
    "GraphFakosVisual",
    "LocalViewerHttpServer",
    "LocalViewerServerResult",
    "RenderPath",
    "build_fixture_baseline_graph",
    "build_fixture_graph",
    "build_fixture_overlay_graphs",
    "build_graph_report",
    "build_graph_diff",
    "build_viewer_route",
    "diagnose_graph",
    "graph_artifact_schema",
    "graph_from_dict",
    "load_comparison_graph",
    "load_graph_artifact",
    "load_overlay_graphs",
    "load_provider_graph",
    "make_local_viewer_server",
    "parse_viewer_request",
    "query_syntax_reference",
    "render_embeddable_html",
    "render_graph_markdown_report",
    "render_graph_fragment",
    "render_graph_viewer",
    "render_provider_path",
    "render_static_html",
    "screen_manifest",
    "serve_local_viewer",
    "validate_graph_artifact_payload",
    "validate_graph",
    "write_graph_artifact",
    "write_embeddable_html",
    "write_graph_markdown_report",
    "write_provider_graph_artifact",
    "write_provider_preview_outputs",
    "write_graph_report",
    "write_static_html",
]
