"""Fake third-party provider used by tests and examples."""

from __future__ import annotations

from graphfakos.models import (
    GraphFakosCitation,
    GraphFakosEdge,
    GraphFakosGraph,
    GraphFakosNode,
    GraphFakosProvenance,
    GraphFakosRequest,
)


def build_fixture_graph(request: GraphFakosRequest | None = None) -> GraphFakosGraph:
    request = request or GraphFakosRequest()
    provenance = (
        GraphFakosProvenance(
            id="prov:fixture",
            provider_id="fixture",
            source_type="third_party",
            source_label="Fixture provider",
            excerpt="Synthetic graph for provider contract tests.",
            observed_at="2026-06-22T00:00:00+00:00",
            confidence=1.0,
        ),
    )
    citations = (
        GraphFakosCitation(
            id="cite:fixture-readme",
            label="Fixture README",
            path="README.md",
            line=1,
            excerpt="Fixture graph source.",
        ),
    )
    nodes = (
        GraphFakosNode(
            id="memory:operator-preference",
            label="Operator Preference",
            kind="memory",
            summary="The operator prefers copyable local validation commands.",
            tags=("preference", "memory"),
            score=0.98,
            source="fixture",
            provenance_ids=("prov:fixture",),
            citation_ids=("cite:fixture-readme",),
        ),
        GraphFakosNode(
            id="document:viewer-spec",
            label="Viewer Spec",
            kind="document",
            summary="Graph viewer requirements for package integration.",
            tags=("document", "viewer"),
            source="fixture",
            provenance_ids=("prov:fixture",),
        ),
        GraphFakosNode(
            id="artifact:static-export",
            label="Static Export",
            kind="artifact",
            summary="Portable HTML export generated by GraphFakos.",
            tags=("artifact", "html"),
            source="fixture",
        ),
        GraphFakosNode(
            id="provider:third-party",
            label="Third-party Provider",
            kind="provider",
            summary="Provider implementing the GraphFakos protocol.",
            tags=("provider", "third_party"),
            source="fixture",
        ),
    )
    edges = (
        GraphFakosEdge(
            id="edge:preference-supports-spec",
            source_id="memory:operator-preference",
            target_id="document:viewer-spec",
            kind="supports",
            label="supports",
            confidence=0.9,
            provenance_ids=("prov:fixture",),
        ),
        GraphFakosEdge(
            id="edge:spec-produces-export",
            source_id="document:viewer-spec",
            target_id="artifact:static-export",
            kind="produces",
            label="produces",
            confidence=0.85,
        ),
        GraphFakosEdge(
            id="edge:provider-serves-spec",
            source_id="provider:third-party",
            target_id="document:viewer-spec",
            kind="serves",
            label="serves",
            confidence=0.88,
        ),
        GraphFakosEdge(
            id="edge:provider-serves-export",
            source_id="provider:third-party",
            target_id="artifact:static-export",
            kind="serves",
            label="serves",
            confidence=0.82,
        ),
    )
    return GraphFakosGraph(
        graph_id="fixture",
        label="Fixture Knowledge Graph",
        provider_id="fixture",
        provider_label="Fixture Provider",
        graph_role="third_party",
        capabilities=(
            "search",
            "neighborhood",
            "path",
            "provenance",
            "provider_status",
            "static_export",
            "local_preview",
        ),
        nodes=nodes,
        edges=edges,
        provenance=provenance,
        citations=citations,
        warnings=(),
        stats={"request_screen": request.screen, "node_count": len(nodes)},
        generated_at="2026-06-22T00:00:00+00:00",
    )


class FixtureGraphProvider:
    provider_id = "fixture"
    provider_label = "Fixture Provider"
    graph_role = "third_party"
    capabilities = (
        "search",
        "neighborhood",
        "path",
        "provenance",
        "provider_status",
        "static_export",
        "local_preview",
    )

    def load_graph(self, request: GraphFakosRequest) -> GraphFakosGraph:
        return build_fixture_graph(request)


__all__ = [
    "FixtureGraphProvider",
    "build_fixture_graph",
]
