"""Fake third-party provider used by tests and examples."""

from __future__ import annotations

from graphfakos.models import (
    GraphFakosCitation,
    GraphFakosEdge,
    GraphFakosGraph,
    GraphFakosNode,
    GraphFakosProvenance,
    GraphFakosRequest,
    GraphFakosSnapshot,
)


def build_fixture_graph(request: GraphFakosRequest | None = None) -> GraphFakosGraph:
    request = request or GraphFakosRequest()
    provenance = (
        GraphFakosProvenance(
            id="prov:fixture",
            provider_id="fixture",
            source_type="third_party",
            source_label="Fixture provider",
            excerpt="Synthetic graph for provider contract tests.",
            observed_at="2026-06-22T00:00:00+00:00",
            confidence=1.0,
        ),
    )
    citations = (
        GraphFakosCitation(
            id="cite:fixture-readme",
            label="Fixture README",
            path="README.md",
            line=1,
            excerpt="Fixture graph source.",
        ),
        GraphFakosCitation(
            id="cite:provider-doc",
            label="Provider Notes",
            path="docs/custom-provider-example.md",
            line=1,
            excerpt="Provider-neutral adapter contract example.",
        ),
    )
    nodes = (
        GraphFakosNode(
            id="memory:operator-preference",
            label="Operator Preference",
            kind="memory",
            summary="The operator prefers copyable local validation commands.",
            tags=("preference", "memory"),
            score=0.98,
            source="fixture",
            timestamps={"observed_at": "2026-06-20T11:00:00+00:00"},
            provenance_ids=("prov:fixture",),
            citation_ids=("cite:fixture-readme",),
        ),
        GraphFakosNode(
            id="document:viewer-spec",
            label="Viewer Spec",
            kind="document",
            summary="Graph viewer requirements for package integration.",
            tags=("document", "viewer"),
            source="fixture",
            timestamps={"updated_at": "2026-06-21T09:30:00+00:00"},
            provenance_ids=("prov:fixture",),
            citation_ids=("cite:provider-doc",),
        ),
        GraphFakosNode(
            id="artifact:static-export",
            label="Static Export",
            kind="artifact",
            summary="Portable HTML export generated by GraphFakos.",
            tags=("artifact", "html"),
            source="fixture",
            timestamps={"generated_at": "2026-06-22T00:00:00+00:00"},
        ),
        GraphFakosNode(
            id="provider:third-party",
            label="Third-party Provider",
            kind="provider",
            summary="Provider implementing the GraphFakos protocol.",
            tags=("provider", "third_party"),
            source="fixture",
            timestamps={"registered_at": "2026-06-19T08:00:00+00:00"},
        ),
    )
    edges = (
        GraphFakosEdge(
            id="edge:preference-supports-spec",
            source_id="memory:operator-preference",
            target_id="document:viewer-spec",
            kind="supports",
            label="supports",
            confidence=0.9,
            provenance_ids=("prov:fixture",),
            citation_ids=("cite:provider-doc",),
        ),
        GraphFakosEdge(
            id="edge:spec-produces-export",
            source_id="document:viewer-spec",
            target_id="artifact:static-export",
            kind="produces",
            label="produces",
            confidence=0.85,
        ),
        GraphFakosEdge(
            id="edge:provider-serves-spec",
            source_id="provider:third-party",
            target_id="document:viewer-spec",
            kind="serves",
            label="serves",
            confidence=0.88,
        ),
        GraphFakosEdge(
            id="edge:provider-serves-export",
            source_id="provider:third-party",
            target_id="artifact:static-export",
            kind="serves",
            label="serves",
            confidence=0.82,
        ),
    )
    return GraphFakosGraph(
        graph_id="fixture",
        label="Fixture Knowledge Graph",
        provider_id="fixture",
        provider_label="Fixture Provider",
        graph_role="third_party",
        capabilities=(
            "search",
            "neighborhood",
            "path",
            "provenance",
            "provider_status",
            "static_export",
            "local_preview",
        ),
        nodes=nodes,
        edges=edges,
        provenance=provenance,
        citations=citations,
        warnings=(),
        stats={"request_screen": request.screen, "node_count": len(nodes)},
        generated_at="2026-06-22T00:00:00+00:00",
        snapshot=GraphFakosSnapshot(
            snapshot_id="fixture-current",
            label="Fixture Current Snapshot",
            created_at="2026-06-22T00:00:00+00:00",
            source_label="Fixture provider graph",
            comparison_ids=("fixture-baseline",),
        ),
        provider_details={
            "owner": "OpenMinion fixture",
            "comparison_mode": "baseline snapshot",
            "overlay_mode": "provider side-by-side",
        },
        capability_details={
            "search": "Structured query terms and facet filters.",
            "neighborhood": "Depth-aware neighborhood expansion around one node.",
            "path": "Shortest-path review across visible graph edges.",
            "provenance": "Evidence-first provenance and citation inspection.",
            "static_export": "Standalone HTML export for debugging and reviews.",
            "local_preview": "Local HTTP preview with shareable route state.",
            "diff": "Snapshot comparison against a provider baseline.",
            "overlay": "Side-by-side provider summary overlays.",
            "embed": "Embeddable fragment for host package UIs.",
            "report": "Machine-readable JSON export for tooling and CI proof.",
        },
        available_facets={
            "node_kind": ("artifact", "document", "memory", "provider"),
            "edge_kind": ("produces", "serves", "supports"),
            "tag": ("artifact", "document", "html", "memory", "preference", "provider", "third_party", "viewer"),
            "source": ("fixture",),
        },
        provider_payload={
            "integration_summary": (
                "This fixture shows how a package-local provider can publish "
                "viewer-ready graph DTOs without importing any host runtime."
            ),
            "integration_commands": (
                "graphfakos-ui --screen explore --html-out graphfakos-ui-preview.html --json",
                "graphfakos-ui --screen provider_status --serve --open",
                "graphfakos-ui --screen diff --report-out graphfakos-report.json --embed-out graphfakos-embed.html --json",
            ),
        },
    )


def build_fixture_baseline_graph(
    request: GraphFakosRequest | None = None,
) -> GraphFakosGraph:
    request = request or GraphFakosRequest(screen="diff", comparison_graph_id="baseline")
    graph = build_fixture_graph(request)
    baseline_nodes = tuple(
        node
        for node in graph.nodes
        if node.id != "artifact:static-export"
    )
    baseline_edges = tuple(
        edge
        for edge in graph.edges
        if edge.id not in {"edge:provider-serves-export", "edge:spec-produces-export"}
    )
    return GraphFakosGraph(
        graph_id="fixture-baseline",
        label="Fixture Knowledge Graph Baseline",
        provider_id="fixture-baseline",
        provider_label="Fixture Baseline",
        graph_role=graph.graph_role,
        capabilities=graph.capabilities,
        nodes=baseline_nodes,
        edges=baseline_edges,
        provenance=graph.provenance,
        citations=graph.citations,
        warnings=("baseline snapshot",),
        stats={"request_screen": request.screen, "node_count": len(baseline_nodes)},
        generated_at="2026-06-18T00:00:00+00:00",
        snapshot=GraphFakosSnapshot(
            snapshot_id="fixture-baseline",
            label="Fixture Baseline Snapshot",
            created_at="2026-06-18T00:00:00+00:00",
            source_label="Fixture baseline graph",
        ),
        provider_details=graph.provider_details,
        capability_details=graph.capability_details,
        available_facets=graph.available_facets,
        provider_payload=graph.provider_payload,
    )


def build_fixture_overlay_graphs(
    request: GraphFakosRequest | None = None,
) -> tuple[GraphFakosGraph, ...]:
    request = request or GraphFakosRequest(screen="provider_status")
    overlay = build_fixture_graph(request)
    companion_nodes = tuple(
        node
        for node in overlay.nodes
        if node.id != "memory:operator-preference"
    )
    companion_edges = tuple(
        edge
        for edge in overlay.edges
        if edge.id != "edge:preference-supports-spec"
    )
    companion = GraphFakosGraph(
        graph_id="fixture-overlay",
        label="Companion Provider Graph",
        provider_id="fixture-overlay",
        provider_label="Overlay Provider",
        graph_role="third_party",
        capabilities=("overlay", "provider_status", "report"),
        nodes=companion_nodes,
        edges=companion_edges,
        provenance=overlay.provenance,
        citations=overlay.citations,
        warnings=("overlay companion",),
        stats={"request_screen": request.screen, "node_count": len(companion_nodes)},
        generated_at="2026-06-21T00:00:00+00:00",
        snapshot=GraphFakosSnapshot(
            snapshot_id="fixture-overlay",
            label="Overlay Snapshot",
            created_at="2026-06-21T00:00:00+00:00",
            source_label="Overlay provider graph",
        ),
        provider_details={"owner": "Overlay fixture"},
        capability_details={"overlay": "Expose a comparison-ready provider summary."},
        available_facets=overlay.available_facets,
        provider_payload=overlay.provider_payload,
    )
    return (companion,)


class FixtureGraphProvider:
    provider_id = "fixture"
    provider_label = "Fixture Provider"
    graph_role = "third_party"
    capabilities = (
        "search",
        "neighborhood",
        "path",
        "provenance",
        "diff",
        "overlay",
        "embed",
        "report",
        "provider_status",
        "static_export",
        "local_preview",
    )

    def load_graph(self, request: GraphFakosRequest) -> GraphFakosGraph:
        return build_fixture_graph(request)

    def load_comparison_graph(
        self,
        request: GraphFakosRequest,
    ) -> GraphFakosGraph:
        return build_fixture_baseline_graph(request)

    def load_overlay_graphs(
        self,
        request: GraphFakosRequest,
    ) -> tuple[GraphFakosGraph, ...]:
        return build_fixture_overlay_graphs(request)


__all__ = [
    "FixtureGraphProvider",
    "build_fixture_baseline_graph",
    "build_fixture_graph",
    "build_fixture_overlay_graphs",
]
